# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - result/*

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "a0d4df40-051c-4431-b25a-b8ec2a271d82"
  imageRepository: "resultapp"
  containerRegistry: "susanazurecicd.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)/result/Dockerfile"
  tag: "$(Build.BuildId)"

  # Agent VM image name
pool:
  name: "azureagent" # Name of your self-hosted agent pool

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            displayName: Build an image to container registry
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              repository: "$(imageRepository)"
              command: "build"
              Dockerfile: "result/Dockerfile"
              tags: "$(tag)"

  - stage: Push
    displayName: Push
    jobs:
      - job: Push
        displayName: Push
        steps:
          - task: Docker@2
            displayName: Push an image to container registry
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              repository: "$(imageRepository)"
              command: "push"
              tags: "$(tag)"

  - stage: Update
    displayName: Update stage
    jobs:
      - job: Update
        displayName: Update
        steps:
          - task: ShellScript@2
            inputs:
              scriptPath: "scripts/updateK8sManifests.sh"
              args: "result $(imageRepository) $(tag)"
