# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - vote/*  # Trigger pipeline when there are changes in the 'vote' directory

resources:
- repo: self  # Reference to the current repository

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd1596a0a-f141-4415-81c9-0ca95eded5f5'  # Your service connection ID
  imageRepository: 'votingapp'  # Name of the image repository
  containerRegistry: 'susanazurecicd.azurecr.io'  # Azure Container Registry URL
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'  # Path to Dockerfile
  tag: '$(Build.BuildId)'  # Tag for the image based on the build ID

# Agent VM
pool:
  name: 'azureagent'  # Name of your self-hosted agent pool

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build

    steps:
    # Step to build the Docker image
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'  # Reference to the service connection
        repository: '$(imageRepository)'  # Image repository name
        command: 'build'  # Command to build the Docker image
        Dockerfile: '$(dockerfilePath)'  # Path to Dockerfile
        tags: '$(tag)'  # Tag for the image (using build ID)

- stage: Push
  displayName: Push stage
  dependsOn: Build  # Ensure this stage runs after Build stage
  jobs:
  - job: Push
    displayName: Push

    steps:
    # Step to push the Docker image to Azure Container Registry
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'  # Reference to the service connection
        repository: '$(imageRepository)'  # Image repository name
        command: 'push'  # Command to push the image
        tags: '$(tag)'  # Tag for the image

- stage: Update
  displayName: Update stage
  jobs:
  - job: Update
    displayName: Update Kubernetes Manifests
    steps:
    # Step to update Kubernetes manifests with the new image tag
    - task: ShellScript@2
      inputs:
        scriptPath: 'scripts/updateK8sManifests.sh'  # Path to the script to update the manifests
        args: 'vote $(imageRepository) $(tag)'  # Pass the repository and tag to the script for updating manifests
